ProyectoWeb/Blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.blog, name="blog"),
    path("categoria/<int:categoria_id>", views.categoria, name="categoria"),
]

ProyectoWeb/Carro/urls.py
from django.urls import path

from . import views

app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("servicios/", include('Servicios.urls')),
    path("", include('ProyectoWebApp.urls')),
    path("blog/", include('Blog.urls')),
    path("contacto/", include('Contacto.urls')),
    path("tienda/", include('Tienda.urls')),
    path("carro/", include('Carro.urls')),
    path("autenticacion/", include('Autenticacion.urls')),
    path("pedidos/", include('Pedidos.urls')),
]

ProyectoWeb/Tienda/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.tienda, name="tienda"),
]

ProyectoWeb/Carro/models.py
from django.db import models

# Create your models here.

ProyectoWeb/Tienda/models.py
from django.db import models

# Create your models here.
class CatProducto(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = 'categoriaPro'
        verbose_name_plural = 'categoriasProd'
        
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50,)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='tienda', blank=True, null=True)
    categoria = models.ForeignKey(CatProducto, on_delete=models.CASCADE)
    disponible = models.BooleanField(default=True)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
        
    def __str__(self):
        return self.nombre

ProyectoWeb/Carro/views.py
from django.shortcuts import render, redirect

from .carro import Carro

from Tienda.models import Producto

# Create your views here.

def agregar_producto(request, producto_id):
    
    carro = Carro(request)
    
    producto = Producto.objects.get(id=producto_id)
    
    carro.agregar(producto)
    
    return redirect('tienda')

def eliminar_producto(request, producto_id):
    
    carro = Carro(request)
    
    producto = Producto.objects.get(id=producto_id)
    
    carro.eliminar(producto)
    
    return redirect('tienda')

def restar_producto(request, producto_id):
    
    carro = Carro(request)
    
    producto = Producto.objects.get(id=producto_id)
    
    carro.restar_producto(producto)
    
    return redirect('tienda')

def limpiar_carro(request):
    
    carro = Carro(request)
    
    carro.limpiar_carro()
    
    return redirect('tienda')

ProyectoWeb/Tienda/views.py
from django.shortcuts import render
from .models import CatProducto, Producto

# Create your views here.
def tienda(request):
    productos = Producto.objects.all()
    return render(request, "Tienda/tienda.html",{"productos":productos})

ProyectoWeb/Tienda/templates/Carro/widget.html
<table class="table table-bordered" style="color: white;">
  <thead>
    <tr>
      <th colspan="3" class="text-center">Carro Compras</th>
    </tr>
    <tr>
      <th>Producto</th>
      <th>Cantidad</th>
      <th>Suma</th>
    </tr>
  </thead>
  <tbody>
    {% if request.session.carro.items %}
      {% for key, value in request.session.carro.items %}
        <tr class="text-center">
          <td>{{ value.nombre }}</td>
          <td>{{ value.cantidad }}</td>
          
          <td>
            <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
            <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
            {{ value.precio }}
          </td>
          
        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="3">
          <div class="alert alert-danger text-center">Sin productos</div>
        </td>
      </tr>
    {% endif %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="3" class="text-center">Total: S/. &nbsp;{{ importe_total_carro }}</td>
    </tr>
    {% if request.session.carro.items %}
      <tr>
        <td colspan="3" class="text-center">
          <a href="../pedidos" class="btn btn-success">Hacer pedido</a>
        </td>
      </tr>
    {% endif %}
  </tfoot>
</table>